#! /usr/bin/env bash

# DISPLAY may not be set, e.g., when ran from cron
: "${DISPLAY:=":0"}"

# Don't run if no display available
xdpyinfo -display "$DISPLAY" >/dev/null 2>&1 || exit

# The path to choose images from
bgdir="/usr/share/backgrounds"

# Number of xscreensaver processes
mapfile -t list < <(pgrep xscreensaver)
# If the screensaver isn't active
if [ "${#list[@]}" -lt 2 ] ; then
  # Fill the choice list when no choices available
  [ -s ~/.fehchoices ] || ls "$bgdir"/*.* > ~/.fehchoices
  # The list of choices
  mapfile -t list < ~/.fehchoices
  # The choice index
  choice=$((RANDOM % ${#list[@]}))
  # Set the background
  DISPLAY="$DISPLAY" /usr/bin/feh -z --bg-fill "${list[choice]}"
  # use a temporary file to trim the list
  tmpfile="$(mktemp)"
  if grep -v "${list[choice]}" ~/.fehchoices > "$tmpfile" ; then
    # the new list is trimmed
    mv "$tmpfile" ~/.fehchoices
  else
    # nothing remaining, remove the tmp file and the list file
    rm -f "$tmpfile" ~/.fehchoices
  fi
fi
